# Generated by Django 3.2.11 on 2022-01-13 08:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2022, 1, 13, 8, 21, 25, 304618, tzinfo=utc), verbose_name='date published')),
                ('update_date', models.DateTimeField(default=datetime.datetime(2022, 1, 13, 8, 21, 25, 304634, tzinfo=utc), verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='Paymenttable',
            fields=[
                ('payment_id', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=2)),
                ('payer_id', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('json_response', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 1, 13, 8, 21, 25, 304243, tzinfo=utc), verbose_name='date published')),
                ('category_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(default='user', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
