# Generated by Django 3.1.14 on 2022-01-10 06:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
